'use client';

import {
  Angry,
  BookOpen,
  Bug,
  Calculator,
  Cat,
  Check,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Crown,
  Dog,
  Drama,
  Flame,
  Footprints,
  Gamepad2,
  Gift,
  Hash,
  Heart,
  HeartHandshake,
  Home,
  Languages,
  Loader2,
  Mars,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Palette,
  Palmtree,
  PawPrint,
  Rainbow,
  Rocket,
  Save,
  Settings,
  Shield,
  Sparkles,
  Square,
  Star,
  Store,
  Sun,
  Umbrella,
  Utensils,
  Venus,
  Volume2,
  X,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';
import { cn } from '@/lib/utils';

export const ICONS = {
  angry: Angry,
  beach: Palmtree,
  book: BookOpen,
  bug: Bug,
  calculator: Calculator,
  cat: Cat,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  cloud: Cloud,
  crown: Crown,
  cuddle: HeartHandshake,
  desert: Sun,
  dog: Dog,
  drama: Drama,
  energy: Zap,
  english: Languages,
  feed: Utensils,
  flame: Flame,
  frog: Bug,
  game: Gamepad2,
  gift: Gift,
  heart: Heart,
  home: Home,
  joy: Sparkles,
  languages: Languages,
  lion: Cat,
  loader: Loader2,
  love: Heart,
  male: Mars,
  message: MessageCircle,
  mic: Mic,
  moon: Moon,
  music: Music,
  numbers: Hash,
  palette: Palette,
  paw: PawPrint,
  play: Gamepad2,
  rainbow: Rainbow,
  rocket: Rocket,
  save: Save,
  settings: Settings,
  shield: Shield,
  shop: Store,
  sing: Music,
  sleep: Moon,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  stop: Square,
  sun: Sun,
  superhero: Shield,
  dinosaur: Footprints,
  animals: PawPrint,
  space: Rocket,
  princess: Crown,
  close: X,
  cross: X,
  stt: Mic,
  tts: Volume2,
  umbrella: Umbrella,
  volume: Volume2,
  wake: Sun,
  female: Venus,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export interface AppIconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
}

export function AppIcon({ name, className, strokeWidth = 2, ...props }: AppIconProps) {
  const Icon = ICONS[name];
  return <Icon className={cn('shrink-0', className)} strokeWidth={strokeWidth} aria-hidden {...props} />;
}
